import type { NextPage } from "next";
import Head from "next/head";
import styled from "styled-components";

// Sections
import Navigation from "../sections/Navigation";
import Header from "../sections/Header";
import About from "../sections/About";
import Work from "../sections/Work";
import Footer from "../sections/Footer";

const Home: NextPage = () => {
  return (
    <PageWrapper>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preload" href="/fonts/Eina/Eina01-Regular.ttf" as="font" crossOrigin="" />
        <link rel="preload" href="/fonts/Eina/Eina02-SemiBold.ttf" as="font" crossOrigin="" />
        <link rel="preload" href="/fonts/Eina/Eina02-Bold.ttf" as="font" crossOrigin="" />
        {/* Whatever */}
        <link rel="preload" href="/fonts/Konkret/Konkret-Thin.woff" as="font" crossOrigin="" />
        <link rel="preload" href="/fonts/Konkret/Konkret-Light.woff" as="font" crossOrigin="" />
        <link rel="preload" href="/fonts/Konkret/Konkret-Regular.woff" as="font" crossOrigin="" />
        <link rel="preload" href="/fonts/Konkret/Konkret-Medium.woff" as="font" crossOrigin="" />
        <link rel="preload" href="/fonts/Konkret/Konkret-Bold.woff" as="font" crossOrigin="" />
        <link rel="preload" href="/fonts/Konkret/Konkret-ExtraBold.woff" as="font" crossOrigin="" />
        <link rel="preload" href="/fonts/Konkret/Konkret-Black.woff" as="font" crossOrigin="" />
      </Head>

      <Main>
        <Navigation />
        <Header />
        <About />
        {/* <Work /> */}
      </Main>

      <Footer />
    </PageWrapper>
  );
};

export default Home;

const PageWrapper = styled.div`
  /* padding: 1rem; */
`;

const Main = styled.main`
  margin: 0 auto;
`;
